# Dockerfile
FROM python:3.12-alpine as common-base

ENV DJANGO_SETTINGS_MODULE=CZERTAINLY_PyADCS_Connector.settings
ENV PYTHONUNBUFFERED=1

RUN apk update && \
  apk add --no-cache gcc python3-dev krb5-dev openssl-dev

# Intermediate image, all compilation takes place here
FROM common-base as builder

RUN pip install -U pip setuptools

RUN mkdir -p /app
WORKDIR /app

RUN apk update && apk add --no-cache build-base python3-dev

RUN mkdir -p /install

COPY django-PyADCSConnector /app
COPY ./CZERTAINLY_PyADCS_Connector /app

RUN sh -c 'pip install --no-warn-script-location --prefix=/install .'
RUN cp -r /install/* /usr/local
#RUN sh -c 'python manage.py collectstatic --no-input'

# Final image, just copy over pre-compiled files
FROM common-base

# add non root user czertainly
RUN addgroup --system --gid 10001 czertainly && adduser --system --home /opt/czertainly --uid 10001 --ingroup czertainly czertainly

COPY docker /
RUN mkdir -p /opt/czertainly

COPY --from=builder /install /usr/local
#COPY --from=builder /app/static.dist /app/static.dist

WORKDIR /opt/czertainly

EXPOSE 8080

USER 10001

ENTRYPOINT ["/opt/czertainly/entry.sh"]
