# Build phase
FROM python:3.13-alpine as build

RUN apk update && \
  apk add --no-cache gcc python3-dev krb5-dev openssl-dev

COPY ./CZERTAINLY_PyADCS_Connector/requirements.txt /opt/czertainly/requirements.txt
RUN pip install -r /opt/czertainly/requirements.txt

# Package phase
FROM python:3.12-alpine

RUN apk update && \
  apk add --no-cache gcc python3-dev krb5-dev openssl-dev

# add non root user czertainly
RUN addgroup --system --gid 10001 czertainly && adduser --system --home /opt/czertainly --uid 10001 --ingroup czertainly czertainly

COPY docker /
COPY --from=build /usr/local/lib/python3.12/site-packages/ /usr/local/lib/python3.12/site-packages/
COPY --from=build /usr/local/bin/ /usr/local/bin/
COPY ./CZERTAINLY_PyADCS_Connector /opt/czertainly

WORKDIR /opt/czertainly

ENV DJANGO_SETTINGS_MODULE=CZERTAINLY_PyADCS_Connector.settings
ENV PYTHONUNBUFFERED=1

EXPOSE 8080

USER 10001

ENTRYPOINT ["/opt/czertainly/entry.sh"]