# Generated by Django 4.2.1 on 2023-05-13 09:53
from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorityInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('https', models.BooleanField(default=False)),
                ('port', models.IntegerField()),
                ('attributes', models.JSONField()),
                ('credential', models.JSONField()),
                ('kind', models.CharField(max_length=100)),
                ('transport', models.CharField(max_length=100, default='credssp')),
            ],
            options={
                'db_table': f'"{settings.DATABASE_SCHEMA}"."authority_instance"',
            },
        ),
        migrations.CreateModel(
            name='DiscoveryCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('base64content', models.TextField()),
                ('discovery_id', models.IntegerField()),
                ('meta', models.JSONField(null=True, default=None)),
            ],
            options={
                'db_table': f'"{settings.DATABASE_SCHEMA}"."discovery_certificate"',
            },
        ),
        migrations.CreateModel(
            name='DiscoveryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField()),
                ('meta', models.JSONField(null=True, default=None)),
            ],
            options={
                'db_table': f'"{settings.DATABASE_SCHEMA}"."discovery_history"',
            },
        ),
    ]
